
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 16 21:05:37 CST 2015
//----------------------------------------------------

package net.learner.practice.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int brown = 21;
  public static final int blue = 15;
  public static final int graph = 9;
  public static final int minus = 3;
  public static final int orange = 19;
  public static final int circle = 10;
  public static final int yellow = 18;
  public static final int red = 16;
  public static final int green = 17;
  public static final int line = 13;
  public static final int purple = 20;
  public static final int polygon = 14;
  public static final int oParen = 6;
  public static final int EOF = 0;
  public static final int square = 11;
  public static final int division = 5;
  public static final int black = 22;
  public static final int error = 1;
  public static final int integer = 23;
  public static final int plus = 2;
  public static final int multiplication = 4;
  public static final int comma = 8;
  public static final int rectangle = 12;
  public static final int cParen = 7;
}

